site_name: Altair EaseViz
site_url: https://miguelub.github.io/altair-easeviz/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: dark
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: orange
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MiguelUB
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguel-huayllas/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/MiguelUB/UbAccesible_altair_theme"  target="_blank" rel="noopener"> Github</a>